import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// KBO Dia Gothic Bold 폰트 설정
const kboDiaGothicBold = localFont({
  src: "./fonts/KBO-Dia-Gothic_bold.woff",
  variable: "--font-kbo-dia-gothic-bold",
  weight: "400 700", // 실제 weight에 맞게 설정
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kboDiaGothicBold.variable}`}>{children}</body>
    </html>
  );
}
